### ISSUE TITLE
Create multimedia page to view individual video (from YT)

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#83]
Please create multimedia page to view individual video (from YT)

**Comment by romnyd** [comment]
![image](https://user-images.githubusercontent.com/4432320/118686393-91f51680-b7c9-11eb-9304-10fa72e3ac46.png)
![image](https://user-images.githubusercontent.com/4432320/118686423-99b4bb00-b7c9-11eb-82f6-69f7279a8fc5.png)

Good morning, perform the implementation in the simplest way since no more mention is mentioned, if you want to install a component, please review me.

@andreaveca

**Comment by romnyd** [comment]
hi @andreaveca can you review

**Comment by andreaveca** [comment]
Hi @romnyd, Good work! This is going to be improved in the future
